from ..Controller.GameController import GameController

def HorseScript1():
    game = GameController(True)
    print(game.GetMoveOption(1, 0, game.red))
    print(game.Red_Move(1, 0, 0, 2))
    print(game.GetMoveOption(0, 2, game.red))
    print(game.board)
    game.Black_Move(1, 0, 2, 2)
    print(game.board)
    game.Red_Move(1, 2, 1, 5)
    print(game.board)
    print(game.GetMoveOption(0, 2, game.red))
    game.Black_Move(2, 3, 2, 4)
    print(game.board)
    game.Red_Move(0, 3, 0, 4)
    print(game.board)
    print(game.GetMoveOption(0, 2, game.red))
    game.Black_Move(2, 2, 3, 4)
    print(game.board)
    game.Red_Move(0, 2, 1, 4)
    print(game.board)
    game.Black_Move(3, 4, 4, 6)
    print(game.board)
    game.Red_Move(1, 4, 2, 6)
    print(game.board)
    print(game.redNext)
    game.Red_Move(1, 4, 3, 5)
    print(game.board)
    game.Black_Move(4, 6, 5, 4)
    print(game.board)
    game.Red_Move(7, 0, 6, 2)
    print(game.board)
    game.Black_Move(6, 3, 6, 4)
    print(game.board)
    print(game.GetMoveOption(1, 5, game.red))
    game.Red_Move(1, 5, 3, 5)
    print(game.board)