from .GameController import GameController

def ChariotScript1():
    game = GameController(True)
    game.PrintBoard()
    print(game.GetMoveOption(0, 0, game.red))
    game.Red_Move(0, 0, 0, 2)
    game.PrintBoard()
    print(game.GetMoveOption(0, 2, game.red))
    print(game.Black_Move(0, 0, 1, 0))
    game.Black_Move(0, 0, 0, 1)
    game.PrintBoard()
    game.Red_Move(0, 2, 0, 1)
    game.PrintBoard()
    game.Black_Move(0, 1, 3, 1)
    game.PrintBoard()
    print(game.Red_Move(0, 1, 5, 1))
    game.PrintBoard()
    game.Black_Move(3, 1, 3, 8)
    game.PrintBoard()
    game.Red_Move(8, 0, 8, 1)
    game.PrintBoard()
    game.Black_Move(3, 8, 4, 8)
    game.PrintBoard()
    game.Red_Move(8, 1, 8, 0)
    game.PrintBoard()
    game.Black_Move(4, 8, 4, 9)
    game.PrintBoard()
    print(game.Red_Move(8, 0, 8, 1))
    game.PrintBoard()