from .GameController import GameController

def ElephantScript1():
    game = GameController(True)
    print(game.board)
    print(game.GetMoveOption(2, 0, game.red))
    print(game.Red_Move(2, 0, 4, 1))
    print(game.Red_Move(2, 0, 4, 2))
    print(game.board)
    print(game.GetMoveOption(4, 2, game.red))
    game.Black_Move(1, 2, 1, 1)
    print(game.board)
    game.Red_Move(2, 3, 2, 4)
    print(game.board)
    print(game.Black_Move(2, 0, 0, 2))
    game.Black_Move(1, 1, 1, 5)
    print(game.board)
    print(game.Red_Move(4, 2, 2, 4))
    game.Red_Move(2, 4, 2, 5)
    print(game.board)
    game.Black_Move(1, 5, 6, 5)
    print(game.board)
    game.Red_Move(4, 2, 2, 4)
    print(game.board)