from .GameController import GameController

def PlayScript(script):
    script()

def SoldierScript1():
    game = GameController(True)
    print(game.red)
    game.Red_Move(0, 3, 0, 4)
    print(game.board)

def SoldierScript2():
    game = GameController(True)
    game.Red_Move(0, 3, 0, 4)
    print(game.board)
    game.Black_Move(8, 3, 8, 4)
    print(game.board)
    game.Red_Move(0, 4, 0, 5)
    print(game.board)
    game.Black_Move(0, 3, 0, 4)
    print(game.board)
    game.Red_Move(0, 5, 1, 5)
    print(game.board)

def SoldierScript3():
    game = GameController(True)
    game.Red_Move(0, 3, 0, 4)
    print(game.board)
    game.Black_Move(8, 3, 8, 4)
    print(game.board)
    game.Red_Move(0, 4, 0, 5)
    print(game.board)
    game.Black_Move(0, 3, 0, 4)
    print(game.board)
    game.Red_Move(0, 5, 1, 5)
    print(game.board)
    game.Black_Move(0, 4, 0, 5)
    print(game.board)
    game.Red_Move(1, 5, 1, 6)
    print(game.board)
    game.Black_Move(0, 5, 0, 6)
    print(game.board)
    game.Red_Move(1, 6, 2, 6)
    print(game.board)
    game.Black_Move(0, 6, 0, 7)
    print(game.board)
    game.Red_Move(2, 3, 2, 4)
    print(game.board)
    game.Black_Move(0, 7, 1, 7)
    print(game.board)
    game.Red_Move(2, 4, 2, 5)
    print(game.board)
    game.Black_Move(1, 7, 2, 7)
    print(game.board)
    print(game.Red_Move(2, 5, 2, 6))
    print(game.board)
    print(game.redNext)